from weibeld/ubuntu-networking
RUN apt-get update
RUN apt-get install nano netcat nmap -y
RUN mkdir /configuration
ADD configuration_CE2.sh configuration/configuration_CE2.sh 
ADD configuration_CE3.sh configuration/configuration_CE3.sh
